networks:
  distributed-system:
    driver: bridge

services:
  coordinator:
    build: .
    image: zero-mq
    command: ["python", "-u", "coordinator.py"]
    networks:
      - distributed-system

  client:
    image: zero-mq
    command: ["python", "-u", "client.py", "5"]
    depends_on:
      - coordinator
    networks:
      - distributed-system
    deploy:
      replicas: 3
