version: "3.9"

networks:
  distributed-system:
    driver: bridge

services:
  server:
    build: .
    image: zero-mq
    command: ["python", "-u", "server.py"]
    networks:
      - distributed-system

  client:
    image: zero-mq
    command: ["python", "-u", "client.py"]
    depends_on:
      - server
    networks:
      - distributed-system
